version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: root

  redis:
    image: 'redis:5'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  app:
    depends_on:
      - postgres
      - redis
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/programador-home-office-api'
      - gems:/gems

volumes:
  redis:
  postgres:
  gems: