version: '2'

services:
  postgres:
    image: 'postgres:12'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:5'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/programador-homeoffice-api'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box: